name: broker_to_tax
description: >-
  A simple cli application that transforms information from brokers to the Portuguese tax information.
version: 1.0.1
homepage: https://github.com/MiguelTVMS/broker_to_tax
repository: https://github.com/MiguelTVMS/broker_to_tax.git
issue_tracker: https://github.com/MiguelTVMS/broker_to_tax/issues
documentation: https://github.com/MiguelTVMS/broker_to_tax#readme

platforms:
  linux:
  macos:
  windows:

publish_to: none

environment:
  sdk: ">=2.19.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.0
  country_code: ^1.0.0
  csv: ^5.0.1
  intl: ^0.18.0
  logging: ^1.1.1
