# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "release/*"
      - "hotfix/*"
      - "main"
    paths:
      - "bin/**"
      - "lib/**"
      - "data/**"
      - ".github/workflows/**"
      - "pubspec.yaml"

    tags:
      - "v**"

jobs:
  unit-test:
    name: Run
    uses: ./.github/workflows/unit-test.yml

  compile:
    name: Run
    needs: unit-test
    uses: ./.github/workflows/compile.yml
